[package]
name = "busser"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Bowman"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
argh = "0.1.10"
chrono = { version = "0.4.24", default-features = false }
csv = "1.1"
serde_json = "1.0.94"

[dev-dependencies]
assert_cmd = "2.0.10"
predicates = "3.0.2"
