use time::format_description::FormatItem;
use time::macros::format_description;

pub const DATE_FORMATS: [&[FormatItem]; 32] = [
    format_description!("[year][first [-] [/] [.]][month padding:none][first [-] [/] [.]][day padding:none]"),
    format_description!("[year][month padding:zero][day padding:zero]"),
    format_description!("[month padding:none]/[day padding:none]/[year]"),
    format_description!("[month padding:none]-[day padding:none]-[year]"),
    format_description!("[year].[month padding:none].[day padding:none]"),
    format_description!("[month padding:none].[day padding:none].[year]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:long]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:short]"),
    format_description!("[year] [month case_sensitive:false repr:long] [day padding:none]"),
    format_description!("[year] [month case_sensitive:false repr:short] [day padding:none]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:long]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:short]"),
    format_description!("[year repr:last_two]-[month padding:none]-[day padding:none]"),
    format_description!("[year repr:last_two][month padding:zero][day padding:none]"),
    format_description!("[month padding:none]/[day padding:none]/[year repr:last_two]"),
    format_description!("[month padding:none]-[day padding:none]-[year repr:last_two]"),
    format_description!("[year repr:last_two].[month padding:none].[day padding:none]"),
    format_description!("[month padding:none].[day padding:none].[year repr:last_two]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year repr:last_two]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year repr:last_two]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year repr:last_two]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year repr:last_two]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:long]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:short]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:long] [day padding:none]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:short] [day padding:none]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:long]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:short]"),
];

pub const TIME_FORMATS: [&[FormatItem]; 1] = [
    format_description!("[first [hour repr:24] [hour repr:12]]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][optional [period case_sensitive:false]]"),
    //format_description!("[hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
];

pub const DATETIME_FORMATS: [&[FormatItem]; 65] = [
    format_description!("[year]-[month padding:none]-[day padding:none]T[hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year]-[month padding:none]-[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year][month padding:zero][day padding:zero] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none]/[day padding:none]/[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none]-[day padding:none]-[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year].[month padding:none].[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none].[day padding:none].[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year] [month case_sensitive:false repr:long] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year] [month case_sensitive:false repr:short] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two]-[month padding:none]-[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two][month padding:zero][day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none]/[day padding:none]/[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none]-[day padding:none]-[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two].[month padding:none].[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month padding:none].[day padding:none].[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:long] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:short] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false]"),
    format_description!("[year]-[month padding:none]-[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year][month padding:zero][day padding:zero] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none]/[day padding:none]/[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none]-[day padding:none]-[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year].[month padding:none].[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none].[day padding:none].[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year] [month case_sensitive:false repr:long] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year] [month case_sensitive:false repr:short] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two]-[month padding:none]-[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two][month padding:zero][day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none]/[day padding:none]/[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none]-[day padding:none]-[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two].[month padding:none].[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month padding:none].[day padding:none].[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:long] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:short] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]]"),
];

pub const DATETIMEOFFSET_FORMATS: [&[FormatItem]; 65] = [
    format_description!("[year]-[month padding:none]-[day padding:none]T[hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year]-[month padding:none]-[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year][month padding:zero][day padding:zero] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]/[day padding:none]/[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]-[day padding:none]-[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year].[month padding:none].[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none].[day padding:none].[year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [month case_sensitive:false repr:long] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [month case_sensitive:false repr:short] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two]-[month padding:none]-[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two][month padding:zero][day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]/[day padding:none]/[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]-[day padding:none]-[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two].[month padding:none].[day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none].[day padding:none].[year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year repr:last_two] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:long] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:short] [day padding:none] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:long] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:short] [hour repr:12]:[minute][optional [:[second]]][optional [.[subsecond]]][optional [ ]][period case_sensitive:false][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year]-[month padding:none]-[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year][month padding:zero][day padding:zero] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]/[day padding:none]/[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]-[day padding:none]-[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year].[month padding:none].[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none].[day padding:none].[year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [month case_sensitive:false repr:long] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [month case_sensitive:false repr:short] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year] [day padding:none] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two]-[month padding:none]-[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two][month padding:zero][day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]/[day padding:none]/[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none]-[day padding:none]-[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two].[month padding:none].[day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month padding:none].[day padding:none].[year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:long] [day padding:none][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[month case_sensitive:false repr:short] [day padding:none][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:long][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [month case_sensitive:false repr:short][optional [,]] [year repr:last_two] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[day padding:none] [year repr:last_two] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:long] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [month case_sensitive:false repr:short] [day padding:none] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:long] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
    format_description!("[year repr:last_two] [day padding:none] [month case_sensitive:false repr:short] [hour repr:24]:[minute][optional [:[second]]][optional [.[subsecond]]][first [offset_hour][:][offset_minute] [ ][offset_hour][:][offset_minute] [Z]]"),
];
